language: "ruby"
script: "bundle exec rake ci"
sudo: false
rvm:
  - 2.5.0
  - 2.6.0
  - 2.7.0
  - jruby-9.1.9.0
env:
  global:
    - JRUBY_OPTS="--2.0"
before_install:
  - "travis_retry gem install bundler"
